repos:
- repo: local
  hooks:
    - id: black
      name: "Checking formatting"
      entry: black --check .
      language: system
      types: [python]
      pass_filenames: false

    - id: isort
      name: "Checking imports"
      entry: isort --check-only .
      language: system
      types: [python]
      pass_filenames: false


    - id: ruff
      name: "Running linter"
      entry: ruff .
      language: system
      types: [python]
      pass_filenames: false
